import type { GuideCard, GuideId } from './types.ts';

const reviewedAt = '2026-09-19';

export const GUIDES: GuideCard[] = [
  {
    id: 'immediate-danger',
    title: 'Get away from immediate danger',
    hazardTags: ['immediate_danger'],
    appliesTo: [],
    urgency: 'immediate',
    steps: [
      'Move to a safer location if you can do so without crossing the hazard.',
      'Call local emergency services if service is available, and follow official alerts or evacuation orders.',
      'Warn nearby people without delaying your own move to safety.',
    ],
    warnings: ['Do not enter a damaged building, floodwater, smoke, or an area that smells of gas.'],
    sourceName: 'Ready.gov',
    sourceUrl: 'https://www.ready.gov/',
    reviewedAt,
  },
  {
    id: 'adult-cpr',
    title: 'Hands-only CPR for an adult',
    hazardTags: ['cardiac_arrest'],
    appliesTo: [],
    urgency: 'immediate',
    steps: [
      'Check that the scene is safe, then check whether the person responds and is breathing normally.',
      'Call emergency services or direct someone else to call, and ask for an AED.',
      'Place the person on their back on a firm, flat surface.',
      'Put both hands in the center of the chest and push hard and fast, 100 to 120 times per minute.',
      'Continue until an AED or trained help takes over, the person shows signs of life, or the scene becomes unsafe.',
    ],
    warnings: ['These hands-only steps are for an adult; children and infants need age-specific care.'],
    sourceName: 'American Red Cross',
    sourceUrl: 'https://www.redcross.org/take-a-class/cpr/performing-cpr/hands-only-cpr',
    reviewedAt,
  },
  {
    id: 'severe-bleeding',
    title: 'Control life-threatening bleeding',
    hazardTags: ['severe_bleeding'],
    appliesTo: [],
    urgency: 'immediate',
    steps: [
      'Call emergency services or direct someone else to call.',
      'Place a dressing or clean cloth over the wound and apply steady, firm pressure directly over it.',
      'Keep pressure on until bleeding stops, a trained responder takes over, or the scene becomes unsafe.',
      'Keep the person from becoming too cold or overheated and watch their breathing and responsiveness.',
    ],
    warnings: ['Use a tourniquet or pack a wound only if trained and the injury is appropriate for that technique.'],
    sourceName: 'American Red Cross',
    sourceUrl: 'https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external',
    reviewedAt,
  },
  {
    id: 'unsafe-water',
    title: 'Treat the water as unsafe',
    hazardTags: ['unsafe_water'],
    appliesTo: [],
    urgency: 'immediate',
    steps: [
      'Use bottled water for drinking, cooking, brushing teeth, preparing food, and making ice when possible.',
      'If officials advise boiling for germs, bring clear water to a rolling boil for 1 minute, then let it cool.',
      'Store treated water in clean, sanitized containers with tight covers.',
    ],
    warnings: ['Boiling does not remove fuel, toxic chemicals, or radioactive material. Use another water source if chemical contamination is possible.'],
    sourceName: 'CDC',
    sourceUrl: 'https://www.cdc.gov/water-emergency/about/index.html',
    reviewedAt,
  },
  {
    id: 'evacuate',
    title: 'Prepare to evacuate safely',
    hazardTags: ['evacuation'],
    appliesTo: [],
    urgency: 'next',
    steps: [
      'Follow evacuation instructions from local officials and leave promptly when directed.',
      'Take essential medications, identification, water, chargers, and only supplies you can carry safely.',
      'Use the recommended route and tell an out-of-area contact where you are going if communication is available.',
    ],
    warnings: ['Do not take shortcuts through floodwater, downed power lines, smoke, or closed roads.'],
    sourceName: 'Ready.gov',
    sourceUrl: 'https://www.ready.gov/evacuation',
    reviewedAt,
  },
  {
    id: 'shelter-in-place',
    title: 'Shelter in place',
    hazardTags: ['shelter'],
    appliesTo: [],
    urgency: 'next',
    steps: [
      'Go to the safest interior location appropriate to the hazard and bring household members and pets with you.',
      'Close and lock exterior doors and windows when officials advise it.',
      'Use a battery radio or saved local alerts for official instructions when available.',
    ],
    warnings: ['The safest room differs by hazard; official evacuation instructions override this general guide.'],
    sourceName: 'Ready.gov',
    sourceUrl: 'https://www.ready.gov/shelter',
    reviewedAt,
  },
  {
    id: 'power-outage',
    title: 'Stay safe during a power outage',
    hazardTags: ['power_outage'],
    appliesTo: [],
    urgency: 'next',
    steps: [
      'Use flashlights instead of candles when possible and disconnect sensitive electronics.',
      'Keep refrigerator and freezer doors closed to preserve cold air.',
      'Check on household members who rely on powered medical or mobility equipment.',
    ],
    warnings: ['Never run a generator, grill, or fuel-burning engine indoors or near windows because carbon monoxide can kill.'],
    sourceName: 'Ready.gov',
    sourceUrl: 'https://www.ready.gov/power-outages',
    reviewedAt,
  },
  {
    id: 'medication-continuity',
    title: 'Protect essential medication',
    hazardTags: ['medication'],
    appliesTo: ['medication'],
    urgency: 'next',
    steps: [
      'Keep medications with the person who needs them, together with labels, dosing instructions, and prescriber information.',
      'Use an insulated container and cold packs for medicine that normally requires refrigeration, without freezing it.',
      'Contact a pharmacist, clinician, or emergency service when available for product-specific storage advice.',
    ],
    warnings: ['Do not change a dose, substitute a medicine, or use medicine that looks damaged based on this app.'],
    sourceName: 'Ready.gov',
    sourceUrl: 'https://www.ready.gov/disability',
    reviewedAt,
  },
  {
    id: 'dependent-support',
    title: 'Support children, older adults, and mobility needs',
    hazardTags: ['accessibility', 'children'],
    appliesTo: ['children', 'older_adults', 'mobility'],
    urgency: 'next',
    steps: [
      'Keep the group together and assign one adult to each person who may need extra help.',
      'Bring mobility devices, communication aids, identification, comfort items, and written care information.',
      'Use simple, calm instructions and confirm that everyone understands the next action.',
    ],
    warnings: ['Do not separate a person from essential assistive equipment unless immediate danger requires moving first.'],
    sourceName: 'Ready.gov',
    sourceUrl: 'https://www.ready.gov/disability',
    reviewedAt,
  },
  {
    id: 'pets',
    title: 'Include pets in the plan',
    hazardTags: ['pets'],
    appliesTo: ['pets'],
    urgency: 'prepare',
    steps: [
      'Keep pets secured with a carrier, leash, or harness and bring identification if available.',
      'Pack pet food, safe water, medication, sanitation supplies, and a familiar item.',
      'Identify a pet-friendly shelter or caregiver when communications become available.',
    ],
    warnings: ['Do not risk entering an unsafe area to retrieve a pet; tell responders where the animal may be.'],
    sourceName: 'Ready.gov',
    sourceUrl: 'https://www.ready.gov/pets',
    reviewedAt,
  },
  {
    id: 'family-reunification',
    title: 'Set a family reunification plan',
    hazardTags: ['reunification'],
    appliesTo: [],
    urgency: 'prepare',
    steps: [
      'Choose one nearby meeting place and one meeting place outside the affected neighborhood.',
      'Choose an out-of-area contact and make sure each household member has the contact written down.',
      'Leave a written note only when safe, stating when you left and the planned destination.',
    ],
    warnings: ['Do not delay an evacuation while waiting at a meeting point that has become unsafe.'],
    sourceName: 'Ready.gov',
    sourceUrl: 'https://www.ready.gov/plan',
    reviewedAt,
  },
  {
    id: 'medical-boundary',
    title: 'Get qualified medical advice',
    hazardTags: ['medication'],
    appliesTo: ['medication'],
    urgency: 'immediate',
    steps: [
      'Do not start, stop, or change a prescription based on this app.',
      'Contact a pharmacist or licensed clinician when service becomes available.',
      'If symptoms may be life-threatening, contact emergency services or seek trained help immediately when it is safe to do so.',
    ],
    warnings: ['FieldLink cannot diagnose a condition or prescribe treatment.'],
    sourceName: 'U.S. Food and Drug Administration',
    sourceUrl: 'https://www.fda.gov/drugs/special-features/medication-health-fraud',
    reviewedAt,
  },
  {
    id: 'earthquake-safety',
    title: 'Stay safe during and after an earthquake',
    hazardTags: ['earthquake'],
    appliesTo: [],
    urgency: 'immediate',
    steps: [
      'During shaking, drop to your hands and knees, cover your head and neck, and hold on to sturdy shelter if available.',
      'After shaking stops, move away from visibly damaged buildings and be ready for aftershocks.',
      'Check yourself and the people with you for injuries, then follow official local instructions when available.',
    ],
    warnings: ['Do not enter a damaged building or use flames if you smell gas.'],
    sourceName: 'Ready.gov',
    sourceUrl: 'https://www.ready.gov/earthquakes',
    reviewedAt,
  },
  {
    id: 'flood-safety',
    title: 'Avoid floodwater and move toward safety',
    hazardTags: ['flood'],
    appliesTo: [],
    urgency: 'immediate',
    steps: [
      'Move to higher ground or a higher level if water is entering your area and you can move safely.',
      'Follow evacuation instructions and use official routes when they are available.',
      'Keep away from bridges over fast-moving water and watch for downed electrical lines.',
    ],
    warnings: ['Do not walk, swim, or drive through floodwater. Turn around and choose another route.'],
    sourceName: 'Ready.gov',
    sourceUrl: 'https://www.ready.gov/floods',
    reviewedAt,
  },
  {
    id: 'wildfire-smoke',
    title: 'Respond to wildfire and heavy smoke',
    hazardTags: ['wildfire_smoke'],
    appliesTo: [],
    urgency: 'immediate',
    steps: [
      'Leave promptly if officials issue an evacuation order and use the recommended route.',
      'If told to remain indoors, close windows and doors and reduce outdoor air entering the building.',
      'Keep medications, identification, water, and essential supplies ready to carry.',
    ],
    warnings: ['Do not wait for visible flames when officials tell your area to evacuate.'],
    sourceName: 'Ready.gov',
    sourceUrl: 'https://www.ready.gov/wildfires',
    reviewedAt,
  },
];

export const GUIDE_BY_ID = new Map<GuideId, GuideCard>(GUIDES.map((guide) => [guide.id, guide]));
